[workspace]
name = "morris_robust"
channels = ["conda-forge", "apple"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[pypi-dependencies]
morris_robust = { path = ".", editable = true }

[dependencies]
python = "3.11.*"
numpy = ">=2.4.6,<3"
salib = ">=1.6.0,<2"
ipython = ">=9.17.1,<10"
ipykernel = ">=7.3.0,<8"
pytest = ">=9.1.1,<10"

[tasks]
tests = "pytest"

